apiVersion: v1
kind: Service
metadata:
  name: appb-service
  labels:
    app: appb
spec:
  selector:
    app: appb
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP