apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ad
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ronakphilipjacob/aks-demo
    targetRevision: HEAD
    path: kubernetes/ad
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true