apiVersion: v2
name: grafana
description: A simple Helm chart for Grafana visualization
type: application
version: 0.1.0
appVersion: "10.1.0"
keywords:
  - grafana
  - monitoring
  - visualization
  - dashboard
home: https://grafana.com/
sources:
  - https://github.com/grafana/grafana