# Default values for grafana chart
replicaCount: 1

image:
  repository: grafana/grafana
  tag: "10.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

admin:
  username: admin
  password: admin123

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

nodeSelector: {}
tolerations: []
affinity: {}