apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  namespace: monitoring
  labels:
    app: grafana-image-renderer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
      - name: grafana-image-renderer
        image: grafana/grafana-image-renderer:3.6.0
        ports:
        - containerPort: 8081
        env:
        - name: ENABLE_METRICS
          value: "true"
        - name: HTTP_PORT
          value: "8081"
        - name: IGNORE_HTTPS_ERRORS
          value: "true"
        - name: RENDERING_ARGS
          value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x720"
        - name: ENABLE_AUTH_TOKEN
          value: "false"
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer-service
  namespace: monitoring
spec:
  selector:
    app: grafana-image-renderer
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP