apiVersion: v1
kind: Service
metadata:
  name: appa-service
  labels:
    app: appa
spec:
  selector:
    app: appa
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer