name: AppB-Service-CI

on:
  pull_request:
    branches: [master]
  push:
    paths:
      - '.github/workflows/app-b.yaml'
      - 'src/appB/**'
  pull_request_target:
    branches: [master]
    paths:
      - '.github/workflows/app-b.yaml'
      - 'src/appB/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/appB
          file: ./src/appB/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/app-b:${{ github.sha }}
          build-args: |
            APPINSIGHTS_INSTRUMENTATION_KEY=${{ secrets.APPINSIGHTS_INSTRUMENTATION_KEY }}
  
  update-k8s-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
       
      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: .*|image: ${{ secrets.ACR_LOGIN_SERVER }}/app-b:${{ github.sha }}|" kubernetes/appB/deployment.yaml
          cat kubernetes/appB/deployment.yaml

      - name: Commit and push updated Kubernetes manifest
        run: |
           git config --global user.email "ronakphilipjacob.rpj@gmail.com"
           git config --global user.name "ronakphilipjacob"
           git add kubernetes/appB/deployment.yaml
           git commit -m "[CI]: Update appB deployment image tag"
           git push