name: Checkout-Service-CI

on:
  pull_request:
    branches: [master]
  push:
    paths:
      - '.github/workflows/checkout.yaml'
      - 'src/checkout/**'
  pull_request_target:
    branches: [master]
    paths:
      - '.github/workflows/checkout.yaml'
      - 'src/checkout/**'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/checkout
          go mod download
          go build -o checkout main.go

      - name: unit tests
        run: |
          cd src/checkout/
          go test -v ./...
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        working-directory: ./src/checkout
        run: |
            go mod tidy
            golangci-lint run ./... --timeout 5m
        continue-on-error: true

  build-and-push:
    runs-on: ubuntu-latest
    needs: [unit-testing, code-quality]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/ad
          file: ./src/ad/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/ad:${{ github.sha }}
  
  update-k8s-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
       
      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: .*|image: ${{ secrets.ACR_LOGIN_SERVER }}/ad:${{ github.sha }}|" kubernetes/ad/deploy.yaml
          cat kubernetes/ad/deploy.yaml

      - name: Commit and push updated Kubernetes manifest
        run: |
           git config --global user.email "ronakphilipjacob.rpj@gmail.com"
           git config --global user.name "ronakphilipjacob"
           git add kubernetes/ad/deploy.yaml
           git commit -m "[CI]: Update ad deployment image tag"
           git push