name: Infrastructure Deployment Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Setup Python for Checkov
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Checkov
      run: pip install checkov

    - name: Copy Terraform Resources
      working-directory: ./terraform/project
      run: cp ../tf_resources/* .

    - name: Terraform Init and Validate
      working-directory: ./terraform/project
      run: |
        export ARM_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}
        terraform init
        terraform validate

    - name: Run Checkov Security Scan
      working-directory: ./terraform/project
      run: |
        checkov -d . --framework terraform --output cli --output sarif --output-file-path checkov-results.sarif
      continue-on-error: true

    - name: Upload Checkov SARIF Results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: ./terraform/project/checkov-results.sarif
        category: checkov-terraform

    - name: Terraform Plan
      working-directory: ./terraform/project
      run: |
        export ARM_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}
        terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./terraform/project
      run: |
        export ARM_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}
        terraform apply -auto-approve tfplan