name: Infrastructure Deployment Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ var.AZURE_CLIENT_ID }}
        tenant-id: ${{ var.AZURE_TENANT_ID }}
        subscription-id: ${{ var.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
        
    - name: Terraform
      working-directory: ./terraform
      run: |
        export ARM_SUBSCRIPTION_ID=${{ var.AZURE_SUBSCRIPTION_ID }}
        terraform init
        terraform validate
        terraform plan -out tfplan
        terraform apply -auto-approve tfplan