# CI for Product Catalog Service
name: Product-Catalog-Service-CI

on:
  pull_request:
    branches: [master]
  push:
    paths:
      - '.github/workflows/product-catalog.yaml'
      - 'src/product-catalog/**'
  pull_request_target:
    branches: [master]
    paths:
      - '.github/workflows/product-catalog.yaml'
      - 'src/product-catalog/**'
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: unit tests
        run: |
          cd src/product-catalog/
          go test -v ./...

  code-quality:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          cd src/product-catalog
          golangci-lint run ./...
        continue-on-error: true

  build-and-push:
    runs-on: ubuntu-latest
    needs: [unit-testing, code-quality]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/product-catalog
          file: ./src/product-catalog/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/product-catalog:${{ github.sha }}
  
  update-k8s-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
       
      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: .*|image: ${{ secrets.ACR_LOGIN_SERVER }}/product-catalog:${{ github.sha }}|" kubernetes/productcatalog/deploy.yaml
          cat kubernetes/productcatalog/deploy.yaml

      - name: Commit and push updated Kubernetes manifest
        run: |
           git config --global user.email "ronakphilipjacob.rpj@gmail.com"
           git config --global user.name "ronakphilipjacob"
           git add kubernetes/productcatalog/deploy.yaml
           git commit -m "[CI]: Update product-catalog deployment image tag"
           git push